version: '3'

services:
  web:
    image: nginx
    ports:
      - "80:80"
    networks:
      - my-network

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - my-network

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - my-network

networks:
  my-network:
